version: "3.0"

services: 
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports: 
      - "0.0.0.0:5432:5432"
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - postgres

  # cruise-ms-domain:
  #   image: domain
  #   container_name: domain-ms
  #   depends_on:
  #     - mongo
